### PR TITLE
trailing white space

### PR DESCRIPTION
**Pull request by jrlevine**
Allow trailing whitespace in DMARC record

### CODE REVIEW

**Comment by alevesely** [comment]
I see no differences, except comment (**MUST**) and vertical alignment.

**Comment by alevesely** [comment]
dmarc-value already includes %20.

**Comment by jrlevine** [comment]
@ale you're right, but dmarc-version does not

**Comment by alevesely** [comment]
Aha, I spotted that *WSP at line 1013.

My understanding then is that the reason why the trailing space was accepted before is the %x20 in dmarc-value.  That is, the accepted value was "100 " (including the trailing space).

**Pull request merged**
